eureka:
  client:
    serivceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: currency-conversion-service
  cloud:
    config:
      enabled: 'false'
      import-check:
        enabled: 'false'
server:
  port: '8100'